# Generated by Django 4.2 on 2023-04-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raktapi', '0002_device_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
