# Generated by Django 4.2 on 2023-05-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raktapi', '0004_product_productgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images/product'),
        ),
    ]
